# Generated by Django 3.2.25 on 2025-08-26 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrationsdb', '0002_author_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='migrationsdb.user', verbose_name='Propietario'),
            preserve_default=False,
        ),
    ]
