# Generated by Django 3.2.25 on 2025-08-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationsdb', '0003_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
