# Generated by Django 3.2.25 on 2025-08-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrationsdb', '0004_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='migrationsdb.Genre', verbose_name='Géneros'),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='migrationsdb.user', verbose_name='Propietario'),
        ),
    ]
