# Generated by Django 3.2.25 on 2025-09-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrationsdb', '0007_auto_20250829_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_all_libraries', 'Puede ver todas las bibliotecas'), ('manage_library', 'Puede gestionar bibliotecas de usuarios'), ('generate_reports', 'Puede generar reportes PDF'), ('import_books', 'Puede importar libros externos')]},
        ),
    ]
